services:
  db:
    image: mysql:5.7
    container_name: db-wp
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_123456
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: 123456
    networks:
      - wpnet
  
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wp
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./themeguillermo:/var/www/html/wp-content/themeguillermo
    ports:
      - 9595:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: 123456
      WORDPRESS_DB_NAME: wordpress
    networks:
      - wpnet

volumes:
  db_data:

networks:
  wpnet: